name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    - name: Make Gradlew Executable
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew build --refresh-dependencies
